action_id: trunk-share-with-everyone
date: 2023-02-25 16:01:09
run: trunk config share --notify --allow-daemon-start=false
run_from: ""
trigger: .git/info/exclude
result:
  exit_code: 127
  out: ""
  err: "trunk-share-with-everyone: trunk: command not found\n"
timestamp: 1677340869
full_timestamp:
  nanos: 902198000
  seconds: 1677340869
trunk_version: 1.5.1
